export const wadCommands = {
  expandWadTreeItem: 'expand_wad_tree_item' as const,
  extractMountedWad: 'extract_mounted_wad' as const,
  extractWadItems: 'extract_wad_items' as const,
  getMountedWad: 'get_mounted_wad' as const,
  getMountedWadDirectoryPathComponents: 'get_mounted_wad_directory_path_components' as const,
  getMountedWads: 'get_mounted_wads' as const,
  getWadItems: 'get_wad_items' as const,
  getWadParentItems: 'get_wad_parent_items' as const,
  getWadTree: 'get_wad_tree' as const,
  mountWads: 'mount_wads' as const,
  moveMountedWad: 'move_mounted_wad' as const,
  searchWad: 'search_wad' as const,
  selectWadTreeItem: 'select_wad_tree_item' as const,
  unmountWad: 'unmount_wad' as const,
  updateMountedWadItemSelection: 'update_mounted_wad_item_selection' as const,
};
