export const wadCommands = {
  expandWadTreeItem: "expand_wad_tree_item",
  extractMountedWad: "extract_mounted_wad",
  extractWadItems: "extract_wad_items",
  getChunkPreviewTypes: "get_chunk_preview_types",
  getImagePreviewUrl: "get_image_preview_url",
  getMountedWad: "get_mounted_wad",
  getMountedWadDirectoryPathComponents:
    "get_mounted_wad_directory_path_components",
  getMountedWads: "get_mounted_wads",
  getWadItems: "get_wad_items",
  getWadParentItems: "get_wad_parent_items",
  getWadTree: "get_wad_tree",
  mountWads: "mount_wads",
  moveMountedWad: "move_mounted_wad",
  searchWad: "search_wad",
  selectWadTreeItem: "select_wad_tree_item",
  unmountWad: "unmount_wad",
  updateMountedWadItemSelection: "update_mounted_wad_item_selection",
} as const;
